import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Header
    'nav.services': 'Services',
    'nav.solutions': 'Solutions', 
    'nav.how-we-work': 'How We Work',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.get-started': 'Get Started',
    
    // Hero
    'hero.subtitle': 'Transform your business with cutting-edge technology solutions that drive growth and innovation',
    'hero.cta': 'Launch Your Project',
    'hero.feature-1': 'Fast Launch',
    'hero.feature-2': 'Clear Vision', 
    'hero.feature-3': 'Deep Insights',
    'hero.feature-4': 'Bright Ideas',
    'hero.feature-5': 'Premium Quality',
    
    // Services
    'services.badge': 'Our Solutions',
    'services.title-1': 'Propel Your Business',
    'services.title-2': 'Into The Future',
    'services.subtitle': 'We help businesses maximize sales and marketing performance through smart analytics and automation, solving today\'s challenges while empowering teams.',
    'services.automation.title': 'Automation & Integration',
    'services.automation.description': 'We create smart systems that connect your tools and streamline complex processes — from CRM and internal communications to project management.',
    'services.automation.feature-1': 'Process optimization',
    'services.automation.feature-2': 'Automated workflow setups',
    'services.automation.feature-3': 'API integrations',
    'services.automation.feature-4': 'Smart notifications',
    'services.analytics.title': 'Data & Analytics',
    'services.analytics.description': 'We turn your data into clear, actionable insights so you can make informed decisions and track real results.',
    'services.analytics.feature-1': 'Interactive dashboards',
    'services.analytics.feature-2': 'Custom metrics',
    'services.analytics.feature-3': 'Data visualization',
    'services.analytics.feature-4': 'Team and process performance analysis',
    'services.ai.title': 'AI & Intelligent Solutions',
    'services.ai.description': 'We leverage AI to boost productivity and accuracy — from client interactions to predictive analytics and automated tools.',
    'services.ai.feature-1': 'Predictive analytics',
    'services.ai.feature-2': 'Text and media analysis',
    'services.ai.feature-3': 'Automation of routine decisions',
    'services.ai.feature-4': 'Smart team support',
    'services.cta-text': 'Do you need an individual project?',
    'services.cta-link': 'Let\'s discuss it together →',
    
    // Features
    'features.title-1': 'Built for the',
    'features.title-2': 'Future of Business',
    'features.subtitle': 'Experience next-generation technology designed to propel your organization beyond today\'s limitations into tomorrow\'s possibilities.',
    'features.expertise.title': 'Proven Expertise',
    'features.expertise.description': 'Over 5 years of experience in EdTech and digital transformation. We understand how technology changes both systems and people.',
    'features.support.title': 'Full-Cycle Support',
    'features.support.description': 'Research, design, development, and ongoing support — we handle it all so you can focus on growth.',
    'features.perspective.title': 'Cross-Industry Perspective',
    'features.perspective.description': 'Our experience spans education, IT, and corporate sectors — allowing us to find creative, practical solutions for every challenge.',
    'features.technology.title': 'Human-Centered Technology',
    'features.technology.description': 'Our tools empower teams, reduce routine, and open up new perspectives.',
    'features.process.research.title': 'Research & Discovery',
    'features.process.research.phase': 'ANALYZE',
    'features.process.design.title': 'Strategic Design',
    'features.process.design.phase': 'PLAN',
    'features.process.prototype.title': 'Rapid Prototyping',
    'features.process.prototype.phase': 'BUILD',
    'features.process.develop.title': 'Full Development',
    'features.process.develop.phase': 'DEPLOY',
    'features.process.test.title': 'Quality Assurance',
    'features.process.test.phase': 'VERIFY',
    'features.process.support.title': 'Ongoing Support',
    'features.process.support.phase': 'MAINTAIN',
    
    // HowWeWork
    'howwework.badge': 'Our Process',
    'howwework.title-1': 'Mission Control:',
    'howwework.title-2': 'How We Launch Success',
    'howwework.subtitle': 'We turn ideas into working digital tools — fast, flexible, and tailored to your business needs.',
    'howwework.step1.title': 'Listen & Explore',
    'howwework.step1.description': 'We start by understanding your goals and how your business really works. Every project begins with people, not code.',
    'howwework.step2.title': 'Plan & Prototype',
    'howwework.step2.description': 'Together, we define the core logic and build quick prototypes to test ideas before full development.',
    'howwework.step3.title': 'Build & Integrate',
    'howwework.step3.description': 'From dashboards and assistants to CRM automations — we create solutions that connect your systems and simplify workflows.',
    'howwework.step4.title': 'Launch & Improve',
    'howwework.step4.description': 'We release fast, test in real conditions, and refine continuously to make tech work smoother every day.',
    'howwework.cta.title': 'Ready to Launch Your Success?',
    'howwework.cta.description': 'From discovery to deployment, we transform your vision into powerful digital solutions that drive real business results.',
    'howwework.cta.button': 'Start Your Mission',
    
    // About
    'about.title-1': 'Mission-Driven',
    'about.title-2': 'Innovation Team',
    'about.description-1': 'Founded by engineers, analysts, and automation experts, Rocket Tech Solution was created with a clear goal — to help businesses grow faster through analytics, automation, and next-generation technology.',
    'about.description-2': 'Our team combines technical precision with business understanding. We make complex digital tools simple, useful, and ready to scale — turning technology from a barrier into a growth driver.',
    'about.description-3': 'We\'re not just integrators — we\'re your partners in progress, helping you move from routine to acceleration.',
    'about.stats.projects': 'Projects Delivered',
    'about.stats.experts': 'Experts in Engineering & Analytics', 
    'about.stats.products': 'AI-Driven Products Launched',
    'about.vision.title': 'Our Vision',
    'about.vision.description': 'To make advanced technologies clear, accessible, and effective for companies of any size — turning digital transformation from a complex project into a clear path to growth.',
    'about.learn-more': 'Learn more about us',
    'about.skills.automation': 'Automation & Bots',
    'about.skills.ai': 'AI & Machine Learning',
    'about.skills.analytics': 'Analytics & BI',
    'about.skills.engineering': 'Product Engineering',
    'about.skills.data': 'Data Architecture', 
    'about.skills.education': 'Education & Mentorship',
    
    // Contact
    'contact.badge': 'Ready to Launch',
    'contact.title-1': 'Let\'s Accelerate',
    'contact.title-2': 'Your Growth Together',
    'contact.subtitle': 'Ready to transform your business? Our mission control team is standing by to chart your course to digital excellence.',
    'contact.form.title': 'Start Your Mission',
    'contact.form.subtitle': 'Tell us about your project and we\'ll craft a custom solution.',
    'contact.form.fullName': 'Full Name',
    'contact.form.fullName.placeholder': 'John Doe',
    'contact.form.email': 'Email Address',
    'contact.form.email.placeholder': 'john@company.com',
    'contact.form.companyName': 'Company Name',
    'contact.form.companyName.placeholder': 'Your Company Ltd.',
    'contact.form.projectDetails': 'Project Details',
    'contact.form.projectDetails.placeholder': 'Tell us about your project, goals, timeline, or any specific requirements...',
    'contact.form.urgent': 'This is an urgent project',
    'contact.form.urgent.description': 'We\'ll prioritize your request for faster response',
    'contact.form.submit': 'Launch Your Project',
    'contact.form.submitting': 'Submitting...',
    'contact.form.security': '🔒 Enterprise-grade security',
    'contact.form.response': '⚡ 48h response time',
    'contact.offer.title': 'Your First Project',
    'contact.offer.description': 'Free consultation + instant discount for new clients.',
    'contact.offer.noFees': 'No hidden fees, no commitments.',
    'contact.training.badge': 'KNOWLEDGE TRANSFER',
    'contact.training.title': 'Not sure where to start?',
    'contact.training.description': 'We offer comprehensive team training and strategic consulting across multiple domains:',
    'contact.training.roadmaps': 'Digital transformation roadmaps',
    'contact.training.ai': 'AI implementation strategies',
    'contact.training.upskilling': 'Team upskilling & workshops',
    'contact.training.cta': 'Let\'s build your team\'s capabilities together',
    'contact.urgent.badge': 'URGENT PROJECT?',
    'contact.urgent.title': 'Quick start',
    'contact.urgent.description': 'We will discuss your project in the next 48 hours and propose the fastest solution.',
    'contact.urgent.note': 'When submitting your request, please indicate if this is an urgent project by checking the corresponding box in the form.',
    'contact.validation.name': 'Please enter your full name',
    'contact.validation.email': 'Please enter a valid email address',
    'contact.success.urgent': 'Urgent project request submitted! We\'ll contact you within 24 hours.',
    'contact.success.normal': 'Project request submitted successfully! We\'ll contact you soon.',
    
    // AllSolutions
    'allsolutions.back': 'Back to Main',
    'allsolutions.title': 'All Solutions',
    'allsolutions.badge': 'Complete Solutions Portfolio',
    'allsolutions.hero.title-1': 'Mission Complete',
    'allsolutions.hero.title-2': 'All Solutions',
    'allsolutions.hero.description': 'Discover our complete portfolio of successful projects across industries. From AI automation to complex business systems — we deliver results that accelerate growth.',
    'allsolutions.stats.total': 'Total Solutions',
    'allsolutions.stats.homepage': 'On Homepage',
    'allsolutions.stats.categories': 'Categories',
    'allsolutions.stats.industries': 'Industries',
    'allsolutions.stats.success': 'Success Rate',
    'allsolutions.search.placeholder': 'Search solutions...',
    'allsolutions.filter.all': 'All',
    'allsolutions.results': 'results',
    'allsolutions.no-results': 'No solutions found matching your criteria.',
    'allsolutions.clear-filters': 'Clear all filters',
    'allsolutions.view-details': 'View Details',
    'allsolutions.learn-more': 'Learn More',
    'allsolutions.get-started': 'Get Started',
    'allsolutions.no-results.title': 'No solutions found',
    'allsolutions.no-results.description': 'Try adjusting your search or filter criteria',
    'allsolutions.no-results.button': 'Clear all filters',
    'allsolutions.modal.ready': 'Ready for Your Own Success Story?',
    'allsolutions.modal.description': 'Let\'s discuss how we can accelerate your project.',

    // CaseStudies
    'casestudies.badge': 'Mission Success Stories',
    'casestudies.title-1': 'Launch Pad',
    'casestudies.title-2': 'Our Solutions',
    'casestudies.subtitle': 'Explore how we\'ve accelerated businesses across industries with our cutting-edge technology solutions and innovation.',
    'casestudies.loading': 'Loading solutions...',
    'casestudies.view-details': 'View Details',
    'casestudies.no-solutions.title': 'No Solutions Selected for Homepage',
    'casestudies.no-solutions.description': 'Our administrators haven\'t selected any solutions to showcase here yet. Check out our complete portfolio to see all available solutions.',
    'casestudies.view-all-solutions': 'View All Solutions',
    'casestudies.more-projects.title': 'Want to see more projects?',
    'casestudies.more-projects.description': 'Our projects are described in more detail in our full portfolio with comprehensive solutions and results.',
    'casestudies.stats.projects': 'Projects Delivered',
    'casestudies.stats.satisfaction': 'Client Satisfaction',
    'casestudies.stats.savings': 'Average Time Savings',
    'casestudies.stats.growth': 'Growth Potential',
    'casestudies.modal.technologies': 'Technologies Used',
    'casestudies.modal.features': 'Unique Features',
    'casestudies.modal.benefits': 'Key Benefits',
    'casestudies.modal.ready': 'Ready for Your Own Success Story?',
    'casestudies.modal.description': 'Let\'s discuss how we can accelerate your project.',
    'casestudies.modal.get-started': 'Get Started',

    // Project Request Modal
    'modal.title': 'Launch Your Project',
    'modal.description': 'Tell us about your project and we\'ll get back to you within 24 hours.',
    'modal.fullName': 'Full Name',
    'modal.fullName.placeholder': 'John Doe',
    'modal.email': 'Email Address', 
    'modal.email.placeholder': 'john@company.com',
    'modal.companyName': 'Company Name',
    'modal.companyName.placeholder': 'Your Company Ltd.',
    'modal.projectDetails': 'Project Details',
    'modal.projectDetails.placeholder': 'Tell us about your project, goals, timeline, or any specific requirements...',
    'modal.isUrgent': 'This is an urgent project',
    'modal.isUrgent.description': 'We\'ll prioritize your request for faster response',
    'modal.cancel': 'Cancel',
    'modal.submit': 'Send Request',
    'modal.submitting': 'Submitting...',
    'modal.validation.name': 'Please enter your full name',
    'modal.validation.email': 'Please enter a valid email address',
    'modal.success.urgent': 'Urgent project request submitted! We\'ll contact you within 24 hours.',
    'modal.success.normal': 'Project request submitted successfully! We\'ll contact you soon.',
    // Footer
    'footer.tagline': 'Automate The Future Today',
    'footer.description': 'While others are still implementing IT, we turn technology into a growth engine that accelerates your business and boosts sales.',
    'footer.email': 'launch@rockettech.solutions',

    'footer.company.title': 'Company',
    'footer.company.about': 'About Us',
    'footer.company.careers': 'Careers',
    'footer.company.solutions': 'Our Solutions',
    'footer.company.blog': 'Blog',
    'footer.company.contact': 'Contact',
    'footer.social.follow': 'Follow our mission:',
    'footer.copyright': '© 2025 Rocket Tech Solution. All rights reserved.',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    
    // Brand Journey
    'brand.journey.title': 'Our Journey',
    'brand.journey.subtitle': 'From first optimizations to complete digital transformation — the evolution of our technological capabilities.',
    'brand.journey.progress.title': 'Automation Progress Overview',
    'brand.journey.progress.subtitle': '2021 → 2025: From manual processes to full automation',
    'brand.journey.automation': 'automation',
    'brand.journey.details.implementations': 'Key Implementations',
    'brand.journey.details.achievements': 'Achievements',
    'brand.journey.details.more': 'Learn more',
    'brand.journey.details.less': 'Show less',
    'brand.journey.stats.years': 'Years of Growth',
    'brand.journey.stats.automation': 'Automation',
    'brand.journey.stats.tools': 'AI Tools',
    'brand.journey.stats.possibilities': 'Possibilities',
    
    'brand.journey.2021.title': 'First Optimizations',
    'brand.journey.2021.description': 'Initial optimization implementations in our company operations',
    'brand.journey.2021.detail1': 'Manual process optimization',
    'brand.journey.2021.detail2': 'Basic task automation',
    'brand.journey.2021.detail3': 'First scripts and tools',
    'brand.journey.2021.achievement1': '5+ processes optimized',
    'brand.journey.2021.achievement2': '10+ hours saved weekly',
    
    'brand.journey.2022.title': 'Analytics & Data Foundation',
    'brand.journey.2022.description': 'First analytics setup and database infrastructure creation',
    'brand.journey.2022.detail1': 'Analytics systems setup',
    'brand.journey.2022.detail2': 'Central database creation',
    'brand.journey.2022.detail3': 'First dashboards and reports',
    'brand.journey.2022.achievement1': '3 databases established',
    'brand.journey.2022.achievement2': 'Complete analytics configured',
    
    'brand.journey.2023.title': 'CRM Automation',
    'brand.journey.2023.description': 'Complete CRM system automation and first external integrations',
    'brand.journey.2023.detail1': '100% CRM automation',
    'brand.journey.2023.detail2': 'External system integrations',
    'brand.journey.2023.detail3': 'Automated sales funnels',
    'brand.journey.2023.achievement1': 'CRM fully automated',
    'brand.journey.2023.achievement2': '10+ integrations created',
    
    'brand.journey.2024.title': 'AI & Bot Integration',
    'brand.journey.2024.description': 'AI bots in communication systems and first AI project implementations',
    'brand.journey.2024.detail1': 'AI support bots',
    'brand.journey.2024.detail2': 'Communication automation',
    'brand.journey.2024.detail3': 'Machine learning in processes',
    'brand.journey.2024.achievement1': '5+ AI bots deployed',
    'brand.journey.2024.achievement2': '50% communication automated',
    
    'brand.journey.2025.title': 'Full Digital Transformation',
    'brand.journey.2025.description': 'Multiple AI tools, complete analytics automation, and partner ecosystem development',
    'brand.journey.2025.detail1': 'Comprehensive AI solutions',
    'brand.journey.2025.detail2': 'Autonomous analytics',
    'brand.journey.2025.detail3': 'Partner solution ecosystem',
    'brand.journey.2025.achievement1': '20+ AI tools deployed',
    'brand.journey.2025.achievement2': 'Full automation achieved',
    
    // Journey Comparison
    'brand.journey.comparison.title': 'Time to Results: Our Journey vs Your Journey',
    'brand.journey.comparison.subtitle': 'We spent years perfecting our expertise so you can achieve automation in weeks, not years.',
    'brand.journey.comparison.years': 'Years',
    'brand.journey.comparison.weeks': 'Weeks',
    'brand.journey.comparison.months': 'Months',
    'brand.journey.comparison.our_journey.title': 'Our Learning Journey',
    'brand.journey.comparison.our_journey.description': 'Five years of research, development, and optimization to master automation technologies and business processes.',
    'brand.journey.comparison.your_journey.title': 'Your Implementation',
    'brand.journey.comparison.your_journey.description': 'Leverage our expertise for rapid deployment of proven automation solutions tailored to your business needs.',
    'brand.journey.comparison.start': 'Start',
    'brand.journey.comparison.launch': 'Launch',
    'brand.journey.comparison.bottom_message': 'Our experience becomes your competitive advantage',
    
    // Brand Platform
    'brand.platform.header.back': 'Back to About Us',
    'brand.platform.header.title': 'Brand Platform',
    'brand.platform.hero.badge': 'RTS Brand Platform',
    'brand.platform.hero.title.line1': 'Beyond Technology',
    'brand.platform.hero.title.line2': 'We are a team',
    'brand.platform.hero.description': 'Rocket Tech Solution isn\'t just a team of developers. We\'re technology partner that helps businesses transform, grow, and achieve more.',
    
    'brand.platform.values.title': 'Our Core Values',
    'brand.platform.values.subtitle': 'These principles guide every decision we make and every solution we deliver.',
    'brand.platform.values.acceleration.title': 'Results Over Process',
    'brand.platform.values.acceleration.description': 'We don\'t just deliver solutions — we accelerate your business growth through cutting-edge technology and strategic innovation.',
    'brand.platform.values.precision.title': 'Simple Solutions',
    'brand.platform.values.precision.description': 'Complex technologies made accessible and barrier-free for everyone.',
    'brand.platform.values.innovation.title': 'Ahead of Time',
    'brand.platform.values.innovation.description': 'We test and implement cutting-edge solutions to keep clients one step ahead.',
    'brand.platform.values.partnership.title': 'Human Technology',
    'brand.platform.values.partnership.description': 'AI and automation do not completely replace people, but help them.',
    
    'brand.platform.principles.title': 'How We Deliver Excellence',
    'brand.platform.principles.subtitle': 'Our methodology combines technical excellence with deep business understanding.',
    'brand.platform.principles.human.title': 'Human-Centered Technology',
    'brand.platform.principles.human.description': 'Technology should serve people, not complicate their lives. We design solutions that feel natural and intuitive.',
    'brand.platform.principles.reliability.title': 'Reliability & Trust',
    'brand.platform.principles.reliability.description': 'Our solutions are built to last, with robust architecture and ongoing support that you can depend on.',
    'brand.platform.principles.excellence.title': 'Excellence in Execution',
    'brand.platform.principles.excellence.description': 'From concept to deployment, we maintain the highest standards of quality and attention to detail.',
    'brand.platform.principles.scalable.title': 'Scalable Growth',
    'brand.platform.principles.scalable.description': 'Every solution is designed with your future growth in mind, ensuring seamless scaling as your business expands.',
    
    'brand.platform.mission.badge': 'Our Mission',
    'brand.platform.mission.quote': 'To transform complex technology into simple, powerful tools that accelerate business growth and human potential.',
    'brand.platform.mission.proven.title': 'Proven Results',
    'brand.platform.mission.proven.description': '50+ successful projects with measurable business impact',
    'brand.platform.mission.rapid.title': 'Rapid Deployment',
    'brand.platform.mission.rapid.description': 'From concept to production in weeks, not months',
    'brand.platform.mission.expert.title': 'Expert Team',
    'brand.platform.mission.expert.description': '10+ specialists across AI, automation, and analytics',
    
    'brand.platform.cta.title': 'Ready to Accelerate Your Growth?',
    'brand.platform.cta.description': 'Join the companies that have transformed their operations with RTS technology solutions.',
    'brand.platform.cta.button': 'Start Your Project',
    
    // Careers Modal
    'careers.title': 'Join Our Team',
    'careers.subtitle': 'Shape the future of technology',
    'careers.intro.title': 'Work with Amazing People',
    'careers.intro.description': 'At RTS, we believe that great technology comes from great teams. Join us in creating innovative solutions that transform businesses and accelerate growth.',
    
    'careers.benefits.title': 'Why Work with Us?',
    'careers.benefits.growth.title': 'Professional Growth',
    'careers.benefits.growth.description': 'Continuous learning opportunities with cutting-edge technologies and industry best practices.',
    'careers.benefits.team.title': 'Collaborative Team',
    'careers.benefits.team.description': 'Work alongside passionate professionals in a supportive and innovative environment.',
    'careers.benefits.projects.title': 'Exciting Projects',
    'careers.benefits.projects.description': 'Challenge yourself with diverse projects that make a real impact on businesses.',
    'careers.benefits.culture.title': 'Great Culture',
    'careers.benefits.culture.description': 'Experience a culture that values creativity, innovation, and work-life balance.',
    
    'careers.opportunities.title': 'Opportunities Available',
    'careers.opportunities.fulltime.title': 'Full-time Positions',
    'careers.opportunities.fulltime.description': 'Join our team as a permanent member and grow your career with us in various technical and business roles.',
    'careers.opportunities.internship.title': 'Internships',
    'careers.opportunities.internship.description': 'Gain valuable experience and learn from industry experts while contributing to real projects.',
    
    'careers.contact.badge': 'Get in Touch',
    'careers.contact.title': 'Ready to Join Us?',
    'careers.contact.description': 'Whether you\'re looking for a full-time position or an internship opportunity, we\'d love to hear from you. Send us your resume and let\'s start a conversation.',
    'careers.contact.email.label': 'Send your resume to:',
    'careers.contact.email.note': 'Include your portfolio and tell us about your passion for technology',
    
    // Contact Modal
    'contact.modal.title': 'Get in Touch',
    'contact.modal.subtitle': 'We\'re here to help',
    'contact.modal.intro.title': 'Let\'s Connect',
    'contact.modal.intro.description': 'Ready to accelerate your business? Our team is standing by to discuss your project and help you achieve your goals.',
    
    'contact.modal.info.title': 'Contact Information',
    'contact.modal.email.label': 'Email us at:',
    'contact.modal.phone.label': 'Call us at:',
    

    
    'contact.modal.cta': 'We typically respond within 24 hours',
  },
  ru: {
    // Header
    'nav.services': 'Услуги',
    'nav.solutions': 'Решения',
    'nav.how-we-work': 'Как мы работаем', 
    'nav.about': 'О нас',
    'nav.contact': 'Контакты',
    'nav.get-started': 'Связаться с нами',
    
    // Hero
    'hero.subtitle': 'Меняем представление о том, как технологии могут развивать бизнес — рост, инновации и эффективность в каждом решении.',
    'hero.cta': 'Обсудить проект',
    'hero.feature-1': 'Быстрый запуск',
    'hero.feature-2': 'Чёткое видение',
    'hero.feature-3': 'Глубокий анализ', 
    'hero.feature-4': 'Яркие идеи',
    'hero.feature-5': 'Премиум качество',
    
    // Services
    'services.badge': 'Решения',
    'services.title-1': 'Развиваем ваш бизнес',
    'services.title-2': 'для будщего',
    'services.subtitle': 'Помогаем компаниям максимизировать показатели продаж и маркетинга через умную аналитику и автоматизацию, решая непростые задачи и расширяя возможности команд.',
    'services.automation.title': 'Автоматизация и интеграция',
    'services.automation.description': 'Создаем умные системы, которые соединяют ваши инструменты и оптимизируют сложные процессы.',
    'services.automation.feature-1': 'Оптимизация процессов',
    'services.automation.feature-2': 'Настройка автоматизированных workflow',
    'services.automation.feature-3': 'API интеграции',
    'services.automation.feature-4': 'Умные уведомления',
    'services.analytics.title': 'Данные и аналитика',
    'services.analytics.description': 'Превращаем данные в понятные и полезные инсайты, чтобы вы могли принимать обоснованные решения и видеть реальные результаты.',
    'services.analytics.feature-1': 'Интерактивные дашборды',
    'services.analytics.feature-2': 'Индивидуальные метрики',
    'services.analytics.feature-3': 'Визуализация данных',
    'services.analytics.feature-4': 'Анализ эффективности команд и процессов',
    'services.ai.title': 'ИИ и интеллектуальные решения',
    'services.ai.description': 'Используем ИИ для повышения продуктивности — от взаимодействия с клиентами до прогнозной аналитики и автоматизированных инструментов.',
    'services.ai.feature-1': 'Прогнозная аналитика',
    'services.ai.feature-2': 'Анализ текста и медиа',
    'services.ai.feature-3': 'Автоматизация рутинных задач',
    'services.ai.feature-4': 'Умная поддержка команды',
    'services.cta-text': 'Необходимо индивидуальное решение?',
    'services.cta-link': 'Давайте обсудим вместе →',
    
    // Features
    'features.title-1': 'Создаём для',
    'features.title-2': 'бизнеса будущего',
    'features.subtitle': 'Познакомьтесь с технологиями нового поколения, разработанные для того, чтобы вывести нас за пределы сегодняшних ограничений в завтрашние возможности.',
    'features.expertise.title': 'Команда экспертов',
    'features.expertise.description': 'Более 5 лет опыта в EdTech и автоматизации. Мы понимаем, как технологии меняют и системы, и людей.',
    'features.support.title': 'Полный цикл поддержки',
    'features.support.description': 'Исследования, аналитика, разработка и постоянная поддержка — мы берем на себя всё, чтобы вы могли сосредоточиться на прибыли.',
    'features.perspective.title': 'Межотраслевая перспектива',
    'features.perspective.description': 'У нас есть опыт в образовании, ИТ и корпоративных секторах. Мы умеем находить креативные, практичные решения для любых задач.',
    'features.technology.title': 'Технологии с заботой',
    'features.technology.description': 'Наши инструменты расширяют возможности команд, уменьшают рутину и открывают новые перспективы.',
    'features.process.research.title': 'Исследования и аналитика',
    'features.process.research.phase': 'ANALYZE',
    'features.process.design.title': 'Конструктивные решения',
    'features.process.design.phase': 'PLAN',
    'features.process.prototype.title': 'Быстрое прототипирование',
    'features.process.prototype.phase': 'BUILD',
    'features.process.develop.title': 'Разработка',
    'features.process.develop.phase': 'DEPLOY',
    'features.process.test.title': 'Обеспечение качества',
    'features.process.test.phase': 'VERIFY',
    'features.process.support.title': 'Поддержка',
    'features.process.support.phase': 'MAINTAIN',
    
    // HowWeWork
    'howwework.badge': 'Процессы',
    'howwework.title-1': 'Центр управления:',
    'howwework.title-2': 'как мы запускаем проекты',
    'howwework.subtitle': 'Превращаем идеи в работающие цифровые инструменты — быстро, гибко и под ваши бизнес-потребности.',
    'howwework.step1.title': 'Слушаем и исследуем',
    'howwework.step1.description': 'Начинаем с понимания ваших целей и того, как работает ваш бизнес. Каждый проект начинается с людей, а не с кода.',
    'howwework.step2.title': 'Планируем и создаём прототипы',
    'howwework.step2.description': 'Вместе определяем основную логику и создаём быстрые прототипы для тестирования идей перед полной разработкой.',
    'howwework.step3.title': 'Создаём и интегрируем',
    'howwework.step3.description': 'От дашбордов и ассистентов до CRM-автоматизации — создаём решения, которые соединяют ваши системы и упрощают процессы.',
    'howwework.step4.title': 'Запускаем и улучшаем',
    'howwework.step4.description': 'Выпускаем быстро, тестируем в реальных условиях и постоянно совершенствуем, чтобы технологии работали ещё лучше каждый день.',
    'howwework.cta.title': 'Построим путь к вашему успеху?',
    'howwework.cta.description': 'От исследования до развёртывания мы превращаем ваше видение в мощные цифровые решения, которые приносят реальные бизнес-результаты.',
    'howwework.cta.button': 'Начать',
    
    // About
    'about.title-1': 'Команда',
    'about.title-2': 'инноваций с миссией',
    'about.description-1': 'Rocket Tech Solution создана инженерами, аналитиками и экспертами по автоматизации, чтобы ускорять рост бизнеса с помощью аналитики, автоматизации и технологий.',
    'about.description-2': 'Наша команда сочетает техническую точность с пониманием бизнеса. Мы делаем сложные цифровые инструменты простыми, полезными и готовыми к масштабированию.',
    'about.description-3': 'Мы не просто интеграторы — мы ваши партнёры в прогрессе, помогающие уйти от рутины.',
    'about.stats.projects': 'Реализованных проектов',
    'about.stats.experts': 'Экспертов в инжиниринге и аналитике',
    'about.stats.products': 'Запущенных AI-продуктов',
    'about.vision.title': 'Наше видение',
    'about.vision.description': 'Сделать технологии понятными, доступными и эффективными для компаний любого размера — превратив автоматизацию из сложного проекта в понятный и эффективный путь к росту.',
    'about.learn-more': 'Узнать больше о нас',
    'about.skills.automation': 'Автоматизация и боты',
    'about.skills.ai': 'ИИ и машинное обучение',
    'about.skills.analytics': 'Аналитика и BI',
    'about.skills.engineering': 'Продуктовая разработка',
    'about.skills.data': 'Архитектура данных',
    'about.skills.education': 'Обучение и менторство',
    
    // Contact
    'contact.badge': 'Запуск',
    'contact.title-1': 'Ускорим ваш рост',
    'contact.title-2': 'вместе',
    'contact.subtitle': 'Готовы трансформировать ваш бизнес? Наша команда миссии готова проложить курс к цифровому совершенству.',
    'contact.form.title': 'Начнем с знакомства',
    'contact.form.subtitle': 'Расскажите нам о вашем проекте, и мы найдем индивидуальное решение.',
    'contact.form.fullName': 'ФИО',
    'contact.form.fullName.placeholder': 'Иван Иванов',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'ivan@company.com',
    'contact.form.companyName': 'Название компании',
    'contact.form.companyName.placeholder': 'Ваша компания',
    'contact.form.projectDetails': 'Детали проекта',
    'contact.form.projectDetails.placeholder': 'Расскажите нам о вашем проекте, целях, временных рамках или любых специфических требованиях...',
    'contact.form.urgent': 'Это срочный проект',
    'contact.form.urgent.description': 'Мы приоритизируем вашу заявку для более быстрого ответа',
    'contact.form.submit': 'Запустить ваш проект',
    'contact.form.submitting': 'Отправка...',
    'contact.form.security': '🔒 Enterprise-grade security',
    'contact.form.response': '⚡ Ответ в течение 48 часов',
    'contact.offer.title': 'Ваш первый проект',
    'contact.offer.description': 'Бесплатная консультация + скидка для новых клиентов.',
    'contact.offer.noFees': 'Никаких скрытых платежей, никаких обязательств.',
    'contact.training.badge': 'ДЕЛИМСЯ ЗНАНИЯМИ',
    'contact.training.title': 'Не знаете, с чего начать?',
    'contact.training.description': 'Мы предлагаем комплексное обучение команд и стратегический консалтинг в различных областях:',
    'contact.training.roadmaps': 'Roadmap автоматизации',
    'contact.training.ai': 'Стратегии внедрения ИИ',
    'contact.training.upskilling': 'Повышение квалификации команд и воркшопы',
    'contact.training.cta': 'Давайте развивать возможности вашей команды вместе',
    'contact.urgent.badge': 'СРОЧНЫЙ ПРОЕКТ?',
    'contact.urgent.title': 'Быстрый старт',
    'contact.urgent.description': 'Мы обсудим ваш проект в течение следующих 48 часов и предложим самое быстрое решение.',
    'contact.urgent.note': 'При отправке заявки, пожалуйста, укажите, является ли это срочным проектом, отметив соответствующий флажок в форме.',
    'contact.validation.name': 'Пожалуйста, введите ваше полное имя',
    'contact.validation.email': 'Пожалуйста, введите корректный email адрес',
    'contact.success.urgent': 'Заявка на срочную консультацию отправлена! Мы свяжемся с вами в течение 24 часов.',
    'contact.success.normal': 'Заявка на консультацию успешно отправлена! Мы скоро свяжемся с вами.',
    
    // AllSolutions
    'allsolutions.back': 'Вернуться на главную',
    'allsolutions.title': 'Все решения',
    'allsolutions.badge': 'Полное портфолио',
    'allsolutions.hero.title-1': 'Миссия выполнима',
    'allsolutions.hero.title-2': 'Все кейсы',
    'allsolutions.hero.description': 'Изучите наше полное портфолио успешных проектов в различных отраслях. От AI-автоматизации до сложных бизнес-систем — мы поставляем результаты, которые ускоряют рост.',
    'allsolutions.stats.total': 'Всего решений',
    'allsolutions.stats.homepage': 'На главной',
    'allsolutions.stats.categories': 'Категорий',
    'allsolutions.stats.industries': 'Отраслей',
    'allsolutions.stats.success': 'Успешность',
    'allsolutions.search.placeholder': 'Поиск решений...',
    'allsolutions.filter.all': 'Все',
    'allsolutions.results': 'результатов',
    'allsolutions.no-results': 'Не найдено решений, соответствующих вашим критериям.',
    'allsolutions.clear-filters': 'Очистить все фильтры',
    'allsolutions.view-details': 'Подробнее',
    'allsolutions.learn-more': 'Узнать больше',
    'allsolutions.get-started': 'Начать',
    'allsolutions.no-results.title': 'Решения не найдены',
    'allsolutions.no-results.description': 'Попробуйте изменить поисковые или фильтрующие критерии',
    'allsolutions.no-results.button': 'Очистить все фильтры',
    'allsolutions.modal.ready': 'Хотите похожее решение или создать что-то уникальное?',
    'allsolutions.modal.description': 'Давайте обсудим ваш проект.',

    // CaseStudies
    'casestudies.badge': 'Истории успеха',
    'casestudies.title-1': 'Стартовая площадка',
    'casestudies.title-2': 'Наши решения',
    'casestudies.subtitle': 'Узнайте, как мы ускорили развитие бизнеса в различных отраслях с помощью наших передовых технологических решений и инноваций.',
    'casestudies.loading': 'Загрузка решений...',
    'casestudies.view-details': 'Подробнее',
    'casestudies.no-solutions.title': 'Не выбрано решений для главной страницы',
    'casestudies.no-solutions.description': 'Наши администраторы пока не выбрали решения для показа здесь. Посмотрите наше полное портфолио, чтобы увидеть все доступные решения.',
    'casestudies.view-all-solutions': 'Посмотреть все кейсы',
    'casestudies.more-projects.title': 'Хотите увидеть больше проектов?',
    'casestudies.more-projects.description': 'Наши проекты в полном портфолио с комплексными решениями и результатами.',
    'casestudies.stats.projects': 'Реализованных проектов',
    'casestudies.stats.satisfaction': 'Удовлетворенность клиентов',
    'casestudies.stats.savings': 'Средняя экономия времени',
    'casestudies.stats.growth': 'Потенциал роста',
    'casestudies.modal.technologies': 'Используемые технологии',
    'casestudies.modal.features': 'Уникальные особенности',
    'casestudies.modal.benefits': 'Ключевые преимущества',
    'casestudies.modal.ready': 'Хотите похожее решение или создать что-то уникальное?',
    'casestudies.modal.description': 'Давайте обсудим ваш проект.',
    'casestudies.modal.get-started': 'Начать',

    // Project Request Modal
    'modal.title': 'Обсудить проект',
    'modal.description': 'Расскажите нам о вашем проекте, и мы свяжемся с вами в течение 24 часов.',
    'modal.fullName': 'ФИО',
    'modal.fullName.placeholder': 'Иван Иванов',
    'modal.email': 'Email адрес', 
    'modal.email.placeholder': 'ivan@company.com',
    'modal.companyName': 'Название компании',
    'modal.companyName.placeholder': 'Ваша компания',
    'modal.projectDetails': 'Детали проекта',
    'modal.projectDetails.placeholder': 'Расскажите нам о вашем проекте, целях, временных рамках или любых специфических требованиях...',
    'modal.isUrgent': 'Это срочный проект',
    'modal.isUrgent.description': 'Мы приоритизируем вашу заявку для более быстрого ответа',
    'modal.cancel': 'Отмена',
    'modal.submit': 'Отправить заявку',
    'modal.submitting': 'Отправка...',
    'modal.validation.name': 'Пожалуйста, введите ваше полное имя',
    'modal.validation.email': 'Пожалуйста, введите корректный email адрес',
    'modal.success.urgent': 'Заявка на срочный проект отправлена! Мы свяжемся с вами в течение 24 часов.',
    'modal.success.normal': 'Заявка на проект успешно отправлена! Мы скоро свяжемся с вами.',

    // Footer
    'footer.tagline': 'Automate The Future Today',
    'footer.description': 'Другие внедряют сложные IT решения, мы ускоряем рост бизнеса и увеличиваем продажи с помощью автоматизации.',
    'footer.email': 'launch@rockettech.solutions',

    'footer.company.title': 'Компания',
    'footer.company.about': 'О нас',
    'footer.company.careers': 'Карьера',
    'footer.company.solutions': 'Наши решения',
    'footer.company.blog': 'Блог',
    'footer.company.contact': 'Контакты',
    'footer.social.follow': 'Следите за нашей миссией:',
    'footer.copyright': '© 2025 Rocket Tech Solution. Все права защищены.',
    'footer.privacy': 'Конфиденциальность',
    'footer.terms': 'Условия',
    
    // Brand Journey
    'brand.journey.title': 'Наш Путь',
    'brand.journey.subtitle': 'От первой оптимизаций до полной автоматизации — эволюция наших технологических возможностей.',
    'brand.journey.progress.title': 'Обзор прогресса автоматизации',
    'brand.journey.progress.subtitle': '2021 → 2025: От ручных процессов к полной автоматизации',
    'brand.journey.automation': 'автоматизации',
    'brand.journey.details.implementations': 'Ключевые внедрения',
    'brand.journey.details.achievements': 'Достижения',
    'brand.journey.details.more': 'Подробнее',
    'brand.journey.details.less': 'Свернуть',
    'brand.journey.stats.years': 'Лет развития',
    'brand.journey.stats.automation': 'Автоматизация',
    'brand.journey.stats.tools': 'AI инструментов',
    'brand.journey.stats.possibilities': 'Возможности',
    
    'brand.journey.2021.title': 'Первые оптимизации',
    'brand.journey.2021.description': 'Начальные внедрения оптимизации в операции нашей компании',
    'brand.journey.2021.detail1': 'Оптимизация ручных процессов',
    'brand.journey.2021.detail2': 'Базовая автоматизация задач',
    'brand.journey.2021.detail3': 'Первые скрипты и инструменты',
    'brand.journey.2021.achievement1': '5+ процессов оптимизировано',
    'brand.journey.2021.achievement2': '10+ часов экономии в неделю',
    
    'brand.journey.2022.title': 'Основа аналитики и данных',
    'brand.journey.2022.description': 'Первая настройка аналитики и создание инфраструктуры баз данных',
    'brand.journey.2022.detail1': 'Настройка систем аналитики',
    'brand.journey.2022.detail2': 'Создание центральных баз данных',
    'brand.journey.2022.detail3': 'Первые дашборды и отчеты',
    'brand.journey.2022.achievement1': '3 базы данных созданы',
    'brand.journey.2022.achievement2': 'Полная аналитика настроена',
    
    'brand.journey.2023.title': 'CRM автоматизация',
    'brand.journey.2023.description': 'Полная автоматизация CRM системы и первые внешние интеграции',
    'brand.journey.2023.detail1': '100% автоматизация CRM',
    'brand.journey.2023.detail2': 'Интеграции с внешними системами',
    'brand.journey.2023.detail3': 'Автоматические воронки продаж',
    'brand.journey.2023.achievement1': 'CRM полностью автоматизирована',
    'brand.journey.2023.achievement2': '10+ интеграций создано',
    
    'brand.journey.2024.title': 'AI и боты',
    'brand.journey.2024.description': 'AI боты в системах общения и первые внедрения AI проектов',
    'brand.journey.2024.detail1': 'AI боты поддержки',
    'brand.journey.2024.detail2': 'Автоматизация коммуникаций',
    'brand.journey.2024.detail3': 'Машинное обучение в процессах',
    'brand.journey.2024.achievement1': '5+ AI ботов внедрено',
    'brand.journey.2024.achievement2': '50% коммуникаций автоматизировано',
    
    'brand.journey.2025.title': 'Полная автоматизация',
    'brand.journey.2025.description': 'Множество AI инструментов, полная автоматизация аналитики и развитие партнерской экосистемы',
    'brand.journey.2025.detail1': 'Комплексные AI решения',
    'brand.journey.2025.detail2': 'Автономная аналитика',
    'brand.journey.2025.detail3': 'Экосистема партнерских решений',
    'brand.journey.2025.achievement1': '20+ AI инструментов внедрено',
    'brand.journey.2025.achievement2': 'Полная автоматизация достигнута',
    
    // Journey Comparison
    'brand.journey.comparison.title': 'Время до результата: Наш путь vs Ваш путь',
    'brand.journey.comparison.subtitle': 'Мы потратили годы на совершенствование, чтобы вы получили результат за недели.',
    'brand.journey.comparison.years': 'Лет',
    'brand.journey.comparison.weeks': 'Недель',
    'brand.journey.comparison.months': 'Месяцев',
    'brand.journey.comparison.our_journey.title': 'Наш путь обучения',
    'brand.journey.comparison.our_journey.description': 'Пять лет исследований, разработки и оптимизации для освоения технологий автоматизации и бизнес-процессов.',
    'brand.journey.comparison.your_journey.title': 'Ваше внедрение',
    'brand.journey.comparison.your_journey.description': 'Быстрое развертывание проверенных решений, адаптированных под ваши бизнес-потребности.',
    'brand.journey.comparison.start': 'Старт',
    'brand.journey.comparison.launch': 'Запуск',
    'brand.journey.comparison.bottom_message': 'Наш опыт становится вашим преимуществом',
    
    // Brand Platform
    'brand.platform.header.back': 'Назад к О нас',
    'brand.platform.header.title': 'Бренд-платформа',
    'brand.platform.hero.badge': 'RTS Бренд-платформа',
    'brand.platform.hero.title.line1': 'За пределами технологий',
    'brand.platform.hero.title.line2': 'Мы - команда',
    'brand.platform.hero.description': 'Rocket Tech Solution — не просто команда разработчиков. Мы технологический партнёр, который помогает бизнесу меняться, расти и достигать большего.',
    
    'brand.platform.values.title': 'Наши основные ценности',
    'brand.platform.values.subtitle': 'Эти принципы лежат в основе каждого принимаемого нами решения и каждого решения, которое мы реализуем.',
    'brand.platform.values.acceleration.title': 'Результат важнее процессов',
    'brand.platform.values.acceleration.description': 'Мы всегда ориентируемся на измеримый эффект для бизнеса.',
    'brand.platform.values.precision.title': 'Простота решений',
    'brand.platform.values.precision.description': 'Сложные технологии объясняем и внедряем так, чтобы ими могли пользоваться без барьеров.',
    'brand.platform.values.innovation.title': 'Опережение времени',
    'brand.platform.values.innovation.description': 'Мы первыми тестируем и внедряем новое, чтобы оставаться на шаг впереди.',
    'brand.platform.values.partnership.title': 'Человечность',
    'brand.platform.values.partnership.description': 'AI и автоматизация не заменяют полностью людей, а помогают их.',
    
    'brand.platform.principles.title': 'Как мы достигаем совершенства',
    'brand.platform.principles.subtitle': 'Наша методология сочетает техническое превосходство с глубоким пониманием бизнеса.',
    'brand.platform.principles.human.title': 'Человеко-ориентированные технологии',
    'brand.platform.principles.human.description': 'Технологии должны служить людям, а не усложнять их жизнь. Мы разрабатываем решения, которые ощущаются естественными и интуитивными.',
    'brand.platform.principles.reliability.title': 'Надёжность и доверие',
    'brand.platform.principles.reliability.description': 'Наши решения созданы для долговечности с надёжной архитектурой и постоянной поддержкой, на которую можно положиться.',
    'brand.platform.principles.excellence.title': 'Превосходство в исполнении',
    'brand.platform.principles.excellence.description': 'От концепции до развёртывания мы поддерживаем высочайшие стандарты качества и внимания к деталям.',
    'brand.platform.principles.scalable.title': 'Масштабируемый рост',
    'brand.platform.principles.scalable.description': 'Каждое решение разработано с учётом вашего будущего роста, обеспечивая бесшовное масштабирование по мере расширения вашего бизнеса.',
    
    'brand.platform.mission.badge': 'Наша миссия',
    'brand.platform.mission.quote': 'Превращать сложные технологии в простые, мощные инструменты, которые ускоряют рост бизнеса и человеческий потенциал.',
    'brand.platform.mission.proven.title': 'Проверенные результаты',
    'brand.platform.mission.proven.description': '50+ успешных проектов с измеримым влиянием на бизнес',
    'brand.platform.mission.rapid.title': 'Быстрое развёртывание',
    'brand.platform.mission.rapid.description': 'От концепции до производства за недели, а не месяцы',
    'brand.platform.mission.expert.title': 'Команда экспертов',
    'brand.platform.mission.expert.description': '10+ специалистов в области ИИ, автоматизации и аналитики',
    
    'brand.platform.cta.title': 'Готовы ускорить свой рост?',
    'brand.platform.cta.description': 'Присоединяйтесь к компаниям, которые трансформировали свои операции с помощью технологических решений RTS.',
    'brand.platform.cta.button': 'Начать проект',
    
    // Careers Modal
    'careers.title': 'Присоединяйтесь к команде',
    'careers.subtitle': 'Формируйте будущее технологий',
    'careers.intro.title': 'Работайте с потрясающими людьми',
    'careers.intro.description': 'В RTS мы верим, что великие технологии создаются великими командами. Присоединяйтесь к нам в создании инновационных решений, которые трансформируют бизнес и ускоряют рост.',
    
    'careers.benefits.title': 'Почему стоит работать с нами?',
    'careers.benefits.growth.title': 'Профессиональный рост',
    'careers.benefits.growth.description': 'Постоянные возможности обучения с передовыми технологиями и лучшими практиками индустрии.',
    'careers.benefits.team.title': 'Команда единомышленников',
    'careers.benefits.team.description': 'Работайте вместе с увлечёнными профессионалами в поддерживающей и инновационной среде.',
    'careers.benefits.projects.title': 'Захватывающие проекты',
    'careers.benefits.projects.description': 'Бросьте себе вызов с разнообразными проектами, которые оказывают реальное влияние на бизнес.',
    'careers.benefits.culture.title': 'Отличная культура',
    'careers.benefits.culture.description': 'Испытайте культуру, которая ценит креативность, инновации и баланс между работой и жизнью.',
    
    'careers.opportunities.title': 'Доступные возможности',
    'careers.opportunities.fulltime.title': 'Постоянные по��иции',
    'careers.opportunities.fulltime.description': 'Присоединяйтесь к нашей команде как постоянный сотрудник и развивайте свою карьеру с нами в различных технических и бизнес-ролях.',
    'careers.opportunities.internship.title': 'Стажировки',
    'careers.opportunities.internship.description': 'Получите ценный опыт и учитесь у экспертов индустрии, внося вклад в реальные проекты.',
    
    'careers.contact.badge': 'Свяжитесь с нами',
    'careers.contact.title': 'Готовы присоединиться?',
    'careers.contact.description': 'Независимо от того, ищете ли вы постоянную позицию или возможность стажировки, мы хотели бы услышать от вас. Отправьте нам своё резюме, и давайте начнём разговор.',
    'careers.contact.email.label': 'Отправьте резюме на:',
    'careers.contact.email.note': 'Включите портфолио и расскажите о своей страсти к технологиям',
    
    // Contact Modal
    'contact.modal.title': 'Свяжитесь с нами',
    'contact.modal.subtitle': 'Мы готовы помочь',
    'contact.modal.intro.title': 'Давайте общаться',
    'contact.modal.intro.description': 'Готовы ускорить развитие своего бизнеса? Наша команда готова обсудить ваш проект и помочь достичь целей.',
    
    'contact.modal.info.title': 'Контактная информация',
    'contact.modal.email.label': 'Напишите нам:',
    'contact.modal.phone.label': 'Позвоните нам:',
    

    
    'contact.modal.cta': 'Мы обычно отвечаем в течение 24 часов',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};